layout: sidebar
style: light

description: >- # this means to ignore newlines until "baseurl:"
#  My projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robch.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:title # URL is the page title

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

twitter:
    username: robethx