title: RobCh.io
email: email
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robch.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Homepage tiles
tiles-source: pages
tiles-count: 6

# Social media
twitter_username: robethx
github_username: robethx
github_url: 
gitlab_url: https://gitlab.com/u/robethx
linkedin_url: 
twitter_url: https://twitter.com/robethx

twitter:
    username: robethx
    
# Default page settings
defaults:
    values:
      sitemap: true
      nav-menu: false
      
collections:
    projects:
        output: true
        permalink: /:name
        